#ifndef MAXENT_H
#define MAXENT_H

enum {
    DESIGN_PIK_VALID = 0,
    DESIGN_LAMBDA,
    DESIGN_EXP_LAMBDA,
    DESIGN_PI_POISSON,
    DESIGN_N,
    DESIGN_N_SAMPLE,
    DESIGN_IDX,
    DESIGN_N_FULL,
    DESIGN_NEWTON_ITERS,
    DESIGN_N_CERTAIN,
    DESIGN_CERTAIN_IDX,
    DESIGN_LENGTH
};

#endif
